// Writes host redirect files from src/data/legacy.mjs so the old .php URLs keep working.
// Hosting is undecided, so every common format is produced:
//   public/_redirects   Netlify, Cloudflare Pages
//   public/.htaccess    Apache (the old site's likely host)
//   vercel.json         Vercel
// Run: node scripts/redirects.mjs   (also runs before every build)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { legacyRedirects } from '../src/data/legacy.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const banner = 'Generated by scripts/redirects.mjs from src/data/legacy.mjs. Edit the data, not this file.';

const seen = new Set();
for (const [from] of legacyRedirects) {
  if (seen.has(from)) throw new Error(`Duplicate legacy redirect: ${from}`);
  seen.add(from);
}

// Netlify / Cloudflare Pages: "from to status". Both treat the fragment as part of the target.
const netlify = [`# ${banner}`, ...legacyRedirects.map(([from, to]) => `${from} ${to} 301`), ''].join('\n');

// Apache: mod_alias Redirect carries the fragment through. Send www to the apex first.
const apache = [
  `# ${banner}`,
  'RewriteEngine On',
  'RewriteCond %{HTTP_HOST} ^www\\.igdrives\\.com$ [NC]',
  'RewriteRule ^(.*)$ https://igdrives.com/$1 [R=301,L,NE]',
  '',
  ...legacyRedirects.map(([from, to]) => {
    const [target, hash] = to.split('#');
    const flags = hash ? 'R=301,L,NE' : 'R=301,L';
    const pattern = `^${from.replace(/^\//, '').replace(/\./g, '\\.')}$`;
    return `RewriteRule ${pattern} ${target}${hash ? `#${hash}` : ''} ${flags}`;
  }),
  '',
].join('\n');

const vercel = JSON.stringify(
  {
    $schema: 'https://openapi.vercel.sh/vercel.json',
    redirects: [
      {
        source: '/:path(.*)',
        has: [{ type: 'host', value: 'www.igdrives.com' }],
        destination: 'https://igdrives.com/:path',
        permanent: true,
      },
      ...legacyRedirects.map(([source, destination]) => ({ source, destination, permanent: true })),
    ],
  },
  null,
  2,
);

fs.mkdirSync(path.join(root, 'public'), { recursive: true });
fs.writeFileSync(path.join(root, 'public/_redirects'), netlify);
fs.writeFileSync(path.join(root, 'public/.htaccess'), apache);
fs.writeFileSync(path.join(root, 'vercel.json'), `${vercel}\n`);
console.log(`${legacyRedirects.length} legacy redirects written for Netlify/Cloudflare, Apache and Vercel`);
